# Generated by Django 5.1.4 on 2024-12-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='time',
        ),
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(default='default_card_id', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='role',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular')], max_length=15),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], max_length=15),
        ),
    ]
