# Generated by Django 5.1.4 on 2024-12-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_card_created_at_alter_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('Activated', 'Activate'), ('Deactivated', 'Deactivate')], max_length=15),
        ),
    ]
