# Generated by Django 5.1.4 on 2024-12-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cardhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardhistory',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='cardhistory',
            name='additional_data',
        ),
        migrations.RemoveField(
            model_name='cardhistory',
            name='card',
        ),
        migrations.RemoveField(
            model_name='cardhistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='card_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cardhistory',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
