# Generated by Django 5.1.4 on 2024-12-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cardactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deactivated_at',
        ),
        migrations.DeleteModel(
            name='CardActionLog',
        ),
    ]
