# Generated by Django 5.1.4 on 2024-12-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_card_deactivated_at_delete_cardactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
