# Generated by Django 5.1.4 on 2025-01-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_card_deactivated_at_card_deactivated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deactivated_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='deactivated_time',
            new_name='created_time',
        ),
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
    ]
