# Generated by Django 5.1.4 on 2025-01-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_deactivatedcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivatedcard',
            name='deactivated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deactivatedcard',
            name='deactivated_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deactivatedcard',
            name='status',
            field=models.CharField(default='Deactivated', max_length=15),
        ),
    ]
