# Generated by Django 5.1.4 on 2025-01-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_log_type_alter_log_date_alter_log_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP')], default='Regular', max_length=15),
        ),
        migrations.AlterField(
            model_name='card',
            name='role',
            field=models.CharField(default='Admin', max_length=15),
        ),
    ]
