# Generated by Django 5.1.4 on 2025-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_card_type_alter_card_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='role',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
