# Generated by Django 5.1.4 on 2025-01-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_card_role_alter_card_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP')], max_length=15),
        ),
    ]
