# Generated by Django 5.1.4 on 2025-01-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular')], max_length=10),
        ),
    ]
