# Generated by Django 5.1.4 on 2025-01-03 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='card_id',
        ),
        migrations.AddField(
            model_name='log',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.card'),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
