# Generated by Django 5.1.4 on 2025-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_log_card_id_log_card_alter_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='card',
        ),
        migrations.AddField(
            model_name='log',
            name='card_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(choices=[('VIP', 'VIP'), ('Regular', 'Regular')], max_length=10),
        ),
    ]
