# Generated by Django 5.1.4 on 2025-01-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_log_card_log_card_id_alter_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
