# Generated by Django 5.1.4 on 2025-01-04 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_log_date_alter_log_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deactivated_date', models.DateField()),
                ('deactivated_time', models.CharField(max_length=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deactivatedcard')),
            ],
        ),
    ]
