# Generated by Django 5.1.4 on 2025-01-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_deactivationevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeactivationEvent',
        ),
    ]
