# Generated by Django 5.1.4 on 2025-01-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_delete_deactivationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivatedcard',
            name='card_id',
            field=models.CharField(max_length=100),
        ),
    ]
